services:
  - type: worker
    name: meme-coin-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHANNEL_ID
        sync: false
      - key: TELEGRAM_API_ID
        sync: false
      - key: TELEGRAM_API_HASH
        sync: false
      - key: ETHEREUM_RPC_URL
        sync: false
      - key: SOLANA_RPC_URL
        sync: false
      - key: DATABASE_URL
        sync: false
